%YAML 1.1
--- !grond.Config
path_prefix: ../..
rundir_template: /home/woxin/Grond/2021_Corinth_5.3/runs/${problem_name}.grun
dataset_config: !grond.DatasetConfig
  stations_stationxml_paths:
  - stations.xml
  events_path: event.txt
  waveform_paths:
  - waveforms
  responses_stationxml_paths:
  - stations.xml
  extend_incomplete: true
  picks_paths: []
  blacklist_paths: []
  blacklist:
  - HL.KLV
  whitelist_paths:
  - whitelist.txt
target_groups:
- !grond.WaveformTargetGroup
  normalisation_family: td
  path: all
  weight: 1.0
  interpolation: nearest_neighbor
  store_id: rigo_gfs
  distance_min: 10000.0
  distance_max: 80000.0
  exclude: []
  channels:
  - N
  - E
  - Z
  misfit_config: !grond.WaveformMisfitConfig
    quantity: displacement
    fmin: 0.05
    fmax: 0.1
    ffactor: 1.5
    tmin: '{stored:begin}-30'
    tmax: '{stored:begin}+40'
    tfade: 20.0
    domain: time_domain
    norm_exponent: 2
    tautoshift_max: 0.0
    autoshift_penalty_max: 0.05
problem_config: !grond.CMTProblemConfig
  name_template: cmt_${event_name}_L1L1_20000
  norm_exponent: 2
  ranges:
    depth: 1000 .. 8000
    duration: 2 .. 8
    east_shift: -5000 .. 5000
    magnitude: 5.1 .. 5.7
    north_shift: -5000 .. 5000
    rmdd: -1.41421 .. 1.41421
    rmed: -1 .. 1
    rmee: -1.41421 .. 1.41421
    rmnd: -1 .. 1
    rmne: -1 .. 1
    rmnn: -1.41421 .. 1.41421
    time: -5 .. 5 | add
  distance_min: 1000.0
  mt_type: full
  stf_type: HalfSinusoidSTF
  nthreads: 1
analyser_configs:
- !grond.TargetBalancingAnalyserConfig
  niterations: 1000
  use_reference_magnitude: false
optimiser_config: !grond.HighScoreOptimiserConfig
  sampler_phases:
  - !grond.UniformSamplerPhase
    niterations: 1000
    ntries_preconstrain_limit: 1000
  - !grond.DirectedSamplerPhase
    niterations: 20000
    ntries_preconstrain_limit: 1000
    scatter_scale_begin: 2.0
    scatter_scale_end: 0.5
    starting_point: excentricity_compensated
    sampler_distribution: normal
    standard_deviation_estimator: median_density_single_chain
    ntries_sample_limit: 1000
  chain_length_factor: 8.0
  nbootstrap: 100
engine_config: !grond.EngineConfig
  gf_stores_from_pyrocko_config: false
  gf_store_superdirs:
  - gf_stores
  gf_store_dirs: []
event_names:
- 2021_Corinth_5.3
event_names_exclude: []
